### ISSUE TITLE
Trying to understand the TicketDispenser example

### ISSUE THREAD

**Issue by saurabhnanda** [advancedtelematic/quickcheck-state-machine#117]
**Is GH the appropriate forum to ask newbie questions?**

Looking at [the ticket dispenser example](https://github.com/advancedtelematic/quickcheck-state-machine/blob/fc8afd449afd823e85c6d733e5e3cc7533eff776/example/src/TicketDispenser.hs) I have the following questions:

* Which part of this is the QC test and which part is the core implementation? I'm guessing [these lines](https://github.com/advancedtelematic/quickcheck-state-machine/blob/fc8afd449afd823e85c6d733e5e3cc7533eff776/example/src/TicketDispenser.hs#L112-L126) are the core implementation of the ticket dispenser, right?
* Looking at the way the core implementation has been written, and what's written in the README as well, i.e. `a datatype of commands;`, does it basically mean that the app needs to be structured like an Elm/React app?
* I'm assuming [this](https://github.com/advancedtelematic/quickcheck-state-machine/blob/fc8afd449afd823e85c6d733e5e3cc7533eff776/example/src/TicketDispenser.hs#L60-L61) is the simplified model against which the real model is being tested, right? What is the phantom type `refs` for?
* Why is a complicated GADT required for the app-wide `Action` data model? Is it because an `Action` is conceptually a representation of a function call which can accept any data-type and return any data-type? Which also brings me to the next question, what if `TakeTicket` could accept the number of tickets the user wants to take? What would the `Action` type look like, in that case?
* Any further explanation of what the [type signature of `semantics` means](https://github.com/advancedtelematic/quickcheck-state-machine/blob/fc8afd449afd823e85c6d733e5e3cc7533eff776/example/src/TicketDispenser.hs#L112-L114) and why is it so complicated?

**Comment by stevana** [comment]
> Is GH the appropriate forum to ask newbie questions?

Sure! Bad documentation is a bug after all...

> Which part of this is the QC test and which part is the core implementation? I'm guessing these lines are the core implementation of the ticket dispenser, right?

That's right.

> Looking at the way the core implementation has been written, and what's written in the README as well, i.e. a datatype of commands;, does it basically mean that the app needs to be structured like an Elm/React app?

I've never seen an Elm or React app, but the library should not force you to structure your program in any particular way -- if you feel that it does then please report a bug.

> I'm assuming this is the simplified model against which the real model is being tested, right?

That's right.

> What is the phantom type refs for?

The library has built in support for reference-like constructs -- that's what `refs` is for. The ticket dispenser example doesn't use any reference-like constructs and hence doesn't use `refs`, but if you look at for example the mutable reference example you'll see how `refs` can be used...

> Why is a complicated GADT required for the app-wide Action data model? Is it because an Action is conceptually a representation of a function call which can accept any data-type and return any data-type? 

Yes, in this case it's a representation of a function call.

> Which also brings me to the next question, what if TakeTicket could accept the number of tickets the user wants to take? What would the Action type look like, in that case?

```
  TakeTicket :: Int -> Action refs ('Response Int)
```

> Any further explanation of what the type signature of semantics means and why is it so complicated?

I will open a PR where I add some more comments to that function during the day, I'll cc you.

**Comment by stevana** [comment]
@saurabhnanda: We made a big refactor of the API in PR #129, could you please revisit the example and check if you find it any easier to understand now? Cheers.

**Comment by stevana** [comment]
Closing; feel free to reopen if you got further questions!
