### ISSUE TITLE
Show instances produce invalid expressions.

### ISSUE THREAD

**Issue by stevana** [advancedtelematic/quickcheck-state-machine#157]
The `Show` instance for `Program` drops `Internal` and `Symbolic` constructors from the output, which produces invalid expressions, e.g.
```
[FillSmall (Var 8), ...]
```
Now that we pretty print the history of a run, instead of the program, we should fix the above and change the `Read` instances accordingly.

**Comment by Lysxia** [comment]
Do you also want to make `Show`/`Read` for the other types more regular as well? For example, `Concrete` and `Symbolic` also omit their constructors when shown.

**Comment by stevana** [comment]
Sure!

By the way, best would be if we could avoid `Read` altogether. It's currently used to read counterexamples from QuickCheck back into programs, so that we can check if they are minimal.

There's this quickcheck-with-counterexample [package](https://hackage.haskell.org/package/quickcheck-with-counterexamples-1.0/docs/Test-QuickCheck-Counterexamples.html), that might help us achieve this?
