### ISSUE TITLE
Question: echo model behaving in an unexpected way

### ISSUE THREAD

**Issue by dnadales** [advancedtelematic/quickcheck-state-machine#218]
I made [a model](https://github.com/dnadales/sandbox/blob/e88cf187c741c31dba82117a4021caf8a15aa9dd/qcsm-echo/test/EchoSpec.hs) from [this](https://github.com/dnadales/sandbox/blob/e88cf187c741c31dba82117a4021caf8a15aa9dd/qcsm-echo/src/Echo.hs) system under test (SUT). The basic idea is that whatever is input to the system is returned afterwards. 

The sequential property passes, as I expected, however the parallel property fails. For instance I see the following failure:

```text
Echo
 │ ┌────────────┐
 │ │ [] ← In "" │
 │ │  → ErrFull │
 │ └────────────┘
  implements echo (parallel) FAILED [1]

Failures:

  test/EchoSpec.hs:42:5:
  1) Echo implements echo (parallel)
       Falsifiable (after 3 tests):
         ParallelCommands
           { prefix = Commands { unCommands = [] }
           , suffixes =
               [ Pair
                   { proj1 = Commands { unCommands = [] }
                   , proj2 =
                       Commands { unCommands = [ Command (In "") (fromList []) ] }
                   }
               ]
           }

  To rerun use: --match "/Echo/implements echo (parallel)/"
```
it seems that the SUT reports that the buffer of size one is full even though no input action is observed in the counter example.

I spent several hours trying to pinpoint the source of the problem without any luck. I read the examples in this repository without finding hints either. 

Any help is greatly appreciated.

**Comment by dnadales** [comment]
Thanks a lot for getting back so quickly. I really appreciate it.

I modified the license as requested. Feel free to include the Echo example in the test suite. If I can help somehow let me know.

**Comment by stevana** [comment]
You're welcome, and thanks letting me use your example!

I think I've found the problem. In order to trigger race conditions more reliably, we rerun the same test case 10 times as part of `runParallelCommands`. Obviously on the second rerun the your `env` might already contain something causing the failure. You can use `runParallelCommandsNTimes 1` instead to avoid this.

There's an open issue about making the rerunning only happen during shrinking, #83, but I don't know how to do that yet.

**Comment by dnadales** [comment]
Great. But I don't understand why adding references solved the problem. Is it because by having the `Env` value be part of the model data avoids sharing?

**Comment by stevana** [comment]
Yeah, with the reference workaround the `mkEnv` happens every time the test case is run, as part of the semantics of `MakeEnv`.

**Comment by dnadales** [comment]
Ok, so that seems to indicate that I was not modeling the example in the right way (at least not the qc-state-machine way).

**Comment by stevana** [comment]
I think if #83 had been fixed, you might not have run into this problem. Except, possibly during shrinking...?

**Comment by Lysxia** [comment]
Maybe the `runner` field could be used to initialize/clean up a property (instantiating `m` with a `ReaderT Env`). In fact it doesn't seem to be used anywhere now.

https://github.com/advancedtelematic/quickcheck-state-machine/blob/5e34578b7958b508d0b019a186f26c1d6a81c82f/src/Test/StateMachine/Types.hs#L70

**Comment by dnadales** [comment]
But then should the echo model be the one that @stevana corrected in my repository? That is, the one in which shared mutable state is avoided in favor of having it being part of the state?

I think the upshot for me was the realization that you could initialize the environment as part of the semantics :)

**Comment by stevana** [comment]
I'm not sure if this would work. As the `mkEnv` and `runReaderT` would happen "outside" of `runParallelCommands` where currently the `monadicIO` is, so `runParallelCommands` would run into the same problem?

Thanks for noticing `runner` is not longer used! I'll remove it from the code.

**Comment by Lysxia** [comment]
You're right, what I had in mind would probably need a bit of rearchitecting so that the "runner" is called inside `runParallelCommands`.

**Comment by stevana** [comment]
Ah, yeah that would be another alternative.
