### ISSUE TITLE
`forAllCommands` generating fewer commands than expected

### ISSUE THREAD

**Issue by m-alvarez** [advancedtelematic/quickcheck-state-machine#299]
I'm using the library to run some tests that crucially depend on the amount of generated commands (for example, say, they will always fail if less than 10 commands have been executed, for internal reasons), and I've found that even if I give `forAllCommands` a large lower bound for the number of commands in a run, in some cases my tests fail because only one or two commands were generated.

I've written a minimum example to check how many commands the library is generating (see [here](https://gist.github.com/m-alvarez/0305497116bfd0845f63518569361ccf)) and it seems like the generated traces vary in size between 20 and 100 - even when giving QuickCheck a larger size parameter, this only seems to affect the maximum number of commands, but not the minimum, which is always lower than 100 - am I missing something? If not, is there any way to make sure every generated sequence of commands has a certain minimum length (other than discarding the shorter ones)?

**Comment by stevana** [comment]
I recently fixed a bug related to this problem, please try using master instead.

**Comment by stevana** [comment]
If that fixes the problem, I can try to make a new release soon.

If you need more fine grained control of how programs are generated, you can also have a look at the Markov [module](https://github.com/advancedtelematic/quickcheck-state-machine/blob/master/src/Test/StateMachine/Markov.hs) and the process registry [example](https://github.com/advancedtelematic/quickcheck-state-machine/blob/master/test/ProcessRegistry.hs) that uses it.

**Comment by m-alvarez** [comment]
Switching to master fixed it, thanks!
