### ISSUE TITLE
Yet another idea how commands could look like

### ISSUE THREAD

**Issue by Danten** [advancedtelematic/quickcheck-state-machine#32]
While looking at the die hard example I noticed that a lot of the functions had to do a lot of unnecessary pattern matching just to refine the type. So I have an idea. 

What if we change the interface (again) to be as follows:
```
ix :: *
cmd :: *
uses :: cmd ~> [ix] 
returns :: cmd ~> Response ix
```

And then we have `Untyped :: Sing cmd - > Env (uses @@ cmd) - > Untyped` where `Env` does whatever we would normally go with `refs`. 

I hope this would achieve a couple of things
1. Allow the constraints to be constant, which would allow definitions to not pattern match unnecessary on the command. 
2. Not force the user of the library to define `IxFunctor` and the rest of the type classes we invented. 
3. The generator and shrink function we need from the user only operates on `cmd` which allows us to completely hide the `Untyped` type from the user. 

I'm sure I'm missing something we're this new scheme is more complicated but since I'm on a mobile I don't know where that would be. 

Extra note, we could split `cmd` further and have a type function for the arguments that will be used for the command (and the only thing that will shrink). The only reason I have so far for this is that we could write a "generic cheat" function for the property that tests that shrink produces sub sequences. Not a biggie so could still be in the `cmd` type for now.

**Comment by stevana** [comment]
We should also reconsider the free monad approach. How far did we get with this approach actually?

**Comment by stevana** [comment]
Another thing that is related: in the union/find example, we could have used the library's support for references, but we had a problem of find returning a new reference that the model didn't know was related to the input. We never figured out a good way to deal with this problem...

**Comment by stevana** [comment]
See also #129.
