### ISSUE TITLE
Drop lts-11 and add lts-14 to Travis CI

### ISSUE THREAD

**Issue by stevana** [advancedtelematic/quickcheck-state-machine#351]
Stack lts-11 builds seems to be timing out on CI, I'm not sure if it's worth keeping around?

On the other hand lts-14 has recently been released and we should add it to the Travis config.

**Comment by kderme** [comment]
Also cabal with 8.2.2 failure on ci https://travis-ci.org/advancedtelematic/quickcheck-state-machine/jobs/577832096.

**Comment by stevana** [comment]
I think that's just a transient error, that build worked fine here: https://travis-ci.org/advancedtelematic/quickcheck-state-machine/builds/577832070?utm_source=github_status&utm_medium=notification

**Comment by kderme** [comment]
I can take a look at this if you like. I`be been anyway fighting with different versions these last days and it's still fresh :)

**Comment by stevana** [comment]
Cool, should be a fairly small change to .travis.yml: remove lts-11 and uncomment lts-13, as lts-14 will be tested by "stack default" I think.

**Comment by stevana** [comment]
Fixed in #353.
