### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by kderme** [advancedtelematic/quickcheck-state-machine#363]
Are there any plans to cut a new release? `ouroboros-consensus` currently depends on an unpublished version, which sometimes is impractical.

**Comment by stevana** [comment]
Sure,can do soon. Most of the work is in updating the changelog. I don't have so much time this week, maybe next?

**Comment by kderme** [comment]
Sure, that's fine. Thanks

**Comment by stevana** [comment]
https://hackage.haskell.org/package/quickcheck-state-machine-0.7.0
